version: "3"

services:
  jupyter:
    # https://hub.docker.com/r/jupyter/base-notebook
    image: jupyter/base-notebook
    volumes:
      - ./docker/jupyter/work:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
